version: '3.8'

services:
  app:
    build:
      context: .
      target: dev
      args:
        NODE_VERSION: ${NODE_VERSION}
        PORT: ${PORT}
        WORKDIR: ${WORKDIR}
    ports:
      - ${PORT}:${PORT}
    volumes:
      - .:${WORKDIR}
      - ${WORKDIR}/node_modules
