version: '3.8'

services:
  app:
    build:
      context: .
      target: prod
      args:
        NODE_VERSION: ${NODE_VERSION}
        PORT: ${PORT}
        WORKDIR: ${WORKDIR}
    restart: always
    ports:
      - ${PORT}:${PORT}
